import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const satoshi = localFont({
  src: "../../public/fonts/satoshi-variable.ttf",
  variable: "--satoshi",
});

const intergralcf = localFont({
  src: [{ path: "../../public/fonts/integralcf-bold.otf", weight: "700" }],
  variable: "--integralcf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${intergralcf.variable} ${satoshi.variable}`}>
      <body>{children}</body>
    </html>
  );
}
